# Generated by Django 6.0.3 on 2026-03-12 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_s',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
            preserve_default=False,
        ),
    ]
