# Generated by Django 6.0.3 on 2026-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_student_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_s',
        ),
        migrations.AddField(
            model_name='course',
            name='student_s',
            field=models.ManyToManyField(to='main.student'),
        ),
    ]
